name: 🐛 Bug Report
labels: ["bug"]
description: |
  Use this template if something is not working as expected.
body:
  - type: markdown
    attributes:
      value: |
        I get an overwhelming of issues which I don't have time to investigate. Most often, they are due to configuration issues. For this reason, I ask you to help me by providing as much information as possible. For issues with `docker-socket-proxy` I may not be able to help as those are not related to Limascope.
  - type: checkboxes
    attributes:
      label: 🔍 Check for existing issues
      description: Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.
      options:
        - label: Completed
          required: true
  - type: dropdown
    attributes:
      label: How is Limascope deployed?
      description: Select the components that you are using.
      options:
        - Standalone Deployment
        - Agents
        - Remote Hosts
        - Swarm Mode
        - Kubernetes
    validations:
      required: true
  - type: input
    attributes:
      label: 📦 Limascope version
      description: Run `docker run Das-Rabindra/limascope --version` or `curl http://<host>/api/version`.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ Command used to run Limascope
      description: Please provide the command used to run Limascope. Provide docker-compose.yml if applicable.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🐛 Describe the bug / provide steps to reproduce it
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: 💻 Environment
      description: Run `docker system info` and paste the output in the field below.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📜 Limascope logs are required for debugging purposes. You may need to enable debug mode. See https://limascope.dev/guide/debugging.
      description: Drag log files or paste the logs into the text input below
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📸 If applicable, add screenshots to help explain your bug
      description: Drag screenshots into the text input below
    validations:
      required: false
