services:
  limascope-service:
    image: Das-Rabindra/limascope:local-test
    environment:
      - DOZZLE_LEVEL=debug
      - DOZZLE_MODE=swarm
    healthcheck:
      test: ["CMD", "/limascope", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
      - limascope
    deploy:
      mode: global

networks:
  limascope:
    driver: overlay
