services:
  limascope:
    image: Das-Rabindra/limascope:latest
    environment:
      - DOZZLE_LEVEL=debug
      - DOZZLE_MODE=swarm
      - DOZZLE_AUTH_PROVIDER=simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: users
        target: /data/users.yml
    ports:
      - "8080:8080"
    networks:
      - limascope
    deploy:
      mode: global

networks:
  limascope:
    driver: overlay
secrets:
  users:
    file: users.yml
